INSERT INTO USERS (ID,NAME, SURNAME, USERNAME, PASSWORD) VALUES (1, 'Usuario1', 'Apellido1', 'US1', 'PASSWORD1');
INSERT INTO USERS (ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES (2, 'Usuario2', 'Apellido2', 'US2', 'PASSWORD2');
INSERT INTO USERS (ID, NAME, SURNAME, USERNAME, PASSWORD) VALUES (3, 'Usuario3', 'Apellido3', 'US3', 'PASSWORD3');

INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 1 de US1', '1');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US1', '1');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US1', '1');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 1 de US2', '2');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US2', '2');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US2', '2');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 1 de US3', '3');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US3', '3');
INSERT INTO TASKS (IS_DONE, DESCRIPTION, USER_ID) VALUES (false, 'Tarea 2 de US3', '3');